// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Backend.Model;

namespace WebApplication.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Accounts.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Contact")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Guest")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParentName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = "0002",
                            Contact = "kontakt",
                            DateOfBirth = new DateTime(2017, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email",
                            Gender = "Zensko",
                            Guest = true,
                            Name = "Jelena",
                            ParentName = "otac",
                            SerialNumber = "0e3f7e4a-d6d5-4a82-b926-f52b4e61d12d",
                            Surname = "Tanjic"
                        },
                        new
                        {
                            Id = "0003",
                            Contact = "kontaktMica",
                            DateOfBirth = new DateTime(2018, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emailMica",
                            Gender = "Zensko",
                            Guest = true,
                            Name = "Sara",
                            ParentName = "mama",
                            SerialNumber = "be4976fa-634b-4878-bec2-c33dcc7b9696",
                            Surname = "Milic"
                        });
                });

            modelBuilder.Entity("Model.Blog.Feedback", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SerialNumber");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Model.MedicalExam.Report", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Findings")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PatientConditions")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PatientId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PatientName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhysitianName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SerialNumber");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            SerialNumber = "04539c87-57f7-4f71-8b56-711c56d8522f",
                            PatientId = "0002",
                            PatientName = "Mika Mikic",
                            PhysitianName = "Pera Peric"
                        },
                        new
                        {
                            SerialNumber = "c1f6087a-f996-4c8a-b04d-1c8b02b2d36d",
                            PatientId = "0002",
                            PatientName = "Mika Mikic",
                            PhysitianName = "Nikola Nikolic"
                        },
                        new
                        {
                            SerialNumber = "12b03d11-c920-4bef-9be2-ed9e0826c8fd",
                            PatientId = "0002",
                            PatientName = "Mika Mikic",
                            PhysitianName = "Bole Bolevic"
                        },
                        new
                        {
                            SerialNumber = "bbc69589-4290-4b28-b237-c5fa93679bd1",
                            PatientId = "0003",
                            PatientName = "Ana Anic",
                            PhysitianName = "Petar Petovic"
                        },
                        new
                        {
                            SerialNumber = "4838da26-ec30-4689-b158-c262af085467",
                            PatientId = "0003",
                            PatientName = "Ana Anic",
                            PhysitianName = "Bole Bolevic"
                        });
                });

            modelBuilder.Entity("health_clinic_class_diagram.Backend.Model.Survey.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionText = "The doctor is welcoming and gentle?"
                        },
                        new
                        {
                            Id = 2,
                            QuestionText = "The doctor answered all of your questions in an understandable manner?"
                        },
                        new
                        {
                            Id = 3,
                            QuestionText = "The doctor takes care of you in a professional manner?"
                        },
                        new
                        {
                            Id = 4,
                            QuestionText = "Would you have the procedure done again by this doctor?"
                        },
                        new
                        {
                            Id = 5,
                            QuestionText = "The personal manner(courtosy,respect,sensitivity,friendliness) of the nurses and other support staff?"
                        },
                        new
                        {
                            Id = 6,
                            QuestionText = "The nursees answered all of your questions in an understandable manner?"
                        },
                        new
                        {
                            Id = 7,
                            QuestionText = "Orientation given to warn setup"
                        },
                        new
                        {
                            Id = 8,
                            QuestionText = "The nurse gave you good discharge instructions"
                        },
                        new
                        {
                            Id = 9,
                            QuestionText = "The nurse was concern for you?"
                        },
                        new
                        {
                            Id = 10,
                            QuestionText = "The comfort and cleanliness of the facility"
                        },
                        new
                        {
                            Id = 11,
                            QuestionText = "Comfort level within the procedure room?"
                        },
                        new
                        {
                            Id = 12,
                            QuestionText = "Conditions of the rooms(temperature,comfort,silence)"
                        },
                        new
                        {
                            Id = 13,
                            QuestionText = "General impression of the ambient atmosphere"
                        },
                        new
                        {
                            Id = 14,
                            QuestionText = "Do you think the clinic has the necessary equipment"
                        },
                        new
                        {
                            Id = 15,
                            QuestionText = "Do you think the clinic's farmacy has the necessary drugs?"
                        },
                        new
                        {
                            Id = 16,
                            QuestionText = "Do you think that the hospital should have more modern equipment than the current one"
                        },
                        new
                        {
                            Id = 17,
                            QuestionText = "Did you noticed broken or damaged equipment in the hospital"
                        },
                        new
                        {
                            Id = 18,
                            QuestionText = "The doctor prescribed medications that I could buy at the clinic's pharmacy"
                        },
                        new
                        {
                            Id = 19,
                            QuestionText = "Did you found it easy to use our website?"
                        },
                        new
                        {
                            Id = 20,
                            QuestionText = "Did you have found all the necessary information on our website?"
                        },
                        new
                        {
                            Id = 21,
                            QuestionText = "Overall, are you satisfied with the care you received in this facility?"
                        },
                        new
                        {
                            Id = 22,
                            QuestionText = "Would you come to this institution again"
                        },
                        new
                        {
                            Id = 23,
                            QuestionText = ">Would you recommend this facility to your friends and family"
                        });
                });

            modelBuilder.Entity("health_clinic_class_diagram.Backend.Model.Survey.Survey", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("DoctorName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question1")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question10")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question11")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question12")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question13")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question14")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question15")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question16")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question17")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question18")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question19")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question20")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question21")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question22")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question23")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question3")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question4")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question5")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question6")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question7")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question8")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Question9")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            ID = "001",
                            DoctorName = "Pera Peric",
                            Question1 = "5",
                            Question10 = "5",
                            Question11 = "2",
                            Question12 = "5",
                            Question13 = "5",
                            Question14 = "5",
                            Question15 = "5",
                            Question16 = "5",
                            Question17 = "5",
                            Question18 = "5",
                            Question19 = "5",
                            Question2 = "5",
                            Question20 = "5",
                            Question21 = "3",
                            Question22 = "2",
                            Question23 = "4",
                            Question3 = "5",
                            Question4 = "5",
                            Question5 = "4",
                            Question6 = "3",
                            Question7 = "5",
                            Question8 = "5",
                            Question9 = "1"
                        },
                        new
                        {
                            ID = "005",
                            DoctorName = "Mika Mikic",
                            Question1 = "5",
                            Question10 = "5",
                            Question11 = "2",
                            Question12 = "5",
                            Question13 = "5",
                            Question14 = "5",
                            Question15 = "5",
                            Question16 = "5",
                            Question17 = "5",
                            Question18 = "5",
                            Question19 = "5",
                            Question2 = "5",
                            Question20 = "5",
                            Question21 = "3",
                            Question22 = "2",
                            Question23 = "4",
                            Question3 = "5",
                            Question4 = "5",
                            Question5 = "4",
                            Question6 = "3",
                            Question7 = "5",
                            Question8 = "5",
                            Question9 = "1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
